import { Employee } from './types';

export const mockEmployees: Employee[] = [
  {
    id: 'EMP001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    role: 'Senior Software Engineer',
    country: 'United States',
    annualSalary: 120000,
    dateOfJoining: new Date('2020-03-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: new Date('2025-12-09').toISOString(),
    probationEndDate: new Date('2020-06-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'Engineering Manager',
    country: 'United States',
    annualSalary: 145000,
    dateOfJoining: new Date('2019-01-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-04-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP003',
    name: 'Miguel Rodriguez',
    email: 'miguel.rodriguez@company.com',
    role: 'Frontend Developer',
    country: 'Spain',
    annualSalary: 65000,
    dateOfJoining: new Date('2021-05-22').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-08-22').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP004',
    name: 'Priya Patel',
    email: 'priya.patel@company.com',
    role: 'Product Manager',
    country: 'India',
    annualSalary: 95000,
    dateOfJoining: new Date('2020-11-03').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-02-03').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP005',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    role: 'CTO',
    country: 'United Kingdom',
    annualSalary: 185000,
    dateOfJoining: new Date('2018-06-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2018-09-01').toISOString(),
    manager: {} as Employee, // No manager (executive),
  },
  {
    id: 'EMP006',
    name: 'Fatima Al-Farsi',
    email: 'fatima.alfarsi@company.com',
    role: 'Backend Developer',
    country: 'United Arab Emirates',
    annualSalary: 78000,
    dateOfJoining: new Date('2022-01-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-04-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP007',
    name: 'Chen Wei',
    email: 'chen.wei@company.com',
    role: 'Data Scientist',
    country: 'China',
    annualSalary: 88000,
    dateOfJoining: new Date('2021-09-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-12-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP008',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@company.com',
    role: 'UX Designer',
    country: 'Canada',
    annualSalary: 82000,
    dateOfJoining: new Date('2020-08-03').toISOString(),
    hireType: 'Agency',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-11-03').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP009',
    name: 'Tomas Novak',
    email: 'tomas.novak@company.com',
    role: 'DevOps Engineer',
    country: 'Czech Republic',
    annualSalary: 72000,
    dateOfJoining: new Date('2021-11-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-02-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP010',
    name: 'Emily Baker',
    email: 'emily.baker@company.com',
    role: 'HR Manager',
    country: 'United States',
    annualSalary: 92000,
    dateOfJoining: new Date('2019-07-12').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-10-12').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP011',
    name: 'Alejandro Gomez',
    email: 'alejandro.gomez@company.com',
    role: 'Software Engineer',
    country: 'Mexico',
    annualSalary: 68000,
    dateOfJoining: new Date('2022-03-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-06-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP012',
    name: 'Sophia Müller',
    email: 'sophia.muller@company.com',
    role: 'Marketing Specialist',
    country: 'Germany',
    annualSalary: 71000,
    dateOfJoining: new Date('2021-02-15').toISOString(),
    hireType: 'Agency',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-05-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP013',
    name: 'Hiroshi Tanaka',
    email: 'hiroshi.tanaka@company.com',
    role: 'QA Engineer',
    country: 'Japan',
    annualSalary: 75000,
    dateOfJoining: new Date('2020-10-05').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-01-05').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP014',
    name: 'Anna Kowalski',
    email: 'anna.kowalski@company.com',
    role: 'Frontend Developer',
    country: 'Poland',
    annualSalary: 62000,
    dateOfJoining: new Date('2022-05-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Contract',
    contractEndDate: new Date('2023-05-10').toISOString(),
    probationEndDate: new Date('2022-08-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP015',
    name: 'Robert Chen',
    email: 'robert.chen@company.com',
    role: 'CFO',
    country: 'United States',
    annualSalary: 175000,
    dateOfJoining: new Date('2018-03-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2018-06-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP016',
    name: 'Olivia Bennett',
    email: 'olivia.bennett@company.com',
    role: 'Content Writer',
    country: 'Australia',
    annualSalary: 65000,
    dateOfJoining: new Date('2021-07-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-10-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP017',
    name: 'Lukas Eriksson',
    email: 'lukas.eriksson@company.com',
    role: 'Backend Developer',
    country: 'Sweden',
    annualSalary: 79000,
    dateOfJoining: new Date('2020-04-12').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-07-12').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP018',
    name: 'Aisha Mbeki',
    email: 'aisha.mbeki@company.com',
    role: 'Data Analyst',
    country: 'South Africa',
    annualSalary: 70000,
    dateOfJoining: new Date('2021-08-05').toISOString(),
    hireType: 'Agency',
    contractType: 'Contract',
    contractEndDate: new Date('2023-08-05').toISOString(),
    probationEndDate: new Date('2021-11-05').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP019',
    name: 'Carlos Santos',
    email: 'carlos.santos@company.com',
    role: 'Project Manager',
    country: 'Brazil',
    annualSalary: 85000,
    dateOfJoining: new Date('2019-10-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-01-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP020',
    name: 'Emma Watson',
    email: 'emma.watson@company.com',
    role: 'Senior UX Designer',
    country: 'United Kingdom',
    annualSalary: 95000,
    dateOfJoining: new Date('2019-05-23').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-08-23').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP021',
    name: 'Raj Sharma',
    email: 'raj.sharma@company.com',
    role: 'DevOps Engineer',
    country: 'India',
    annualSalary: 76000,
    dateOfJoining: new Date('2020-09-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-12-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP022',
    name: 'Natalie Kim',
    email: 'natalie.kim@company.com',
    role: 'Product Designer',
    country: 'South Korea',
    annualSalary: 80000,
    dateOfJoining: new Date('2021-01-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-04-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP023',
    name: 'David Mitchell',
    email: 'david.mitchell@company.com',
    role: 'Sales Manager',
    country: 'Canada',
    annualSalary: 105000,
    dateOfJoining: new Date('2019-04-05').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-07-05').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP024',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@company.com',
    role: 'Graphic Designer',
    country: 'Italy',
    annualSalary: 67000,
    dateOfJoining: new Date('2022-02-15').toISOString(),
    hireType: 'Agency',
    contractType: 'Contract',
    contractEndDate: new Date('2023-02-15').toISOString(),
    probationEndDate: new Date('2022-05-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP025',
    name: 'Ahmed Al-Mansour',
    email: 'ahmed.almansour@company.com',
    role: 'Software Engineer',
    country: 'Egypt',
    annualSalary: 58000,
    dateOfJoining: new Date('2021-06-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-09-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP026',
    name: 'Marie Dubois',
    email: 'marie.dubois@company.com',
    role: 'Frontend Developer',
    country: 'France',
    annualSalary: 73000,
    dateOfJoining: new Date('2020-07-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-10-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP027',
    name: 'Sven Jorgensen',
    email: 'sven.jorgensen@company.com',
    role: 'System Administrator',
    country: 'Denmark',
    annualSalary: 76000,
    dateOfJoining: new Date('2021-03-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-06-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP028',
    name: 'Jasmine Wong',
    email: 'jasmine.wong@company.com',
    role: 'Marketing Manager',
    country: 'Singapore',
    annualSalary: 90000,
    dateOfJoining: new Date('2019-09-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-12-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP029',
    name: 'Victor Okafor',
    email: 'victor.okafor@company.com',
    role: 'Data Scientist',
    country: 'Nigeria',
    annualSalary: 72000,
    dateOfJoining: new Date('2022-01-05').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-04-05').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP030',
    name: 'Ana Silva',
    email: 'ana.silva@company.com',
    role: 'Customer Support Lead',
    country: 'Portugal',
    annualSalary: 62000,
    dateOfJoining: new Date('2020-11-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-02-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP031',
    name: 'Thomas Wagner',
    email: 'thomas.wagner@company.com',
    role: 'Senior Backend Developer',
    country: 'Germany',
    annualSalary: 98000,
    dateOfJoining: new Date('2019-03-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-06-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP032',
    name: 'Sofia Garcia',
    email: 'sofia.garcia@company.com',
    role: 'Junior Software Engineer',
    country: 'Spain',
    annualSalary: 55000,
    dateOfJoining: new Date('2022-04-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-07-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP033',
    name: 'Alexander Kim',
    email: 'alexander.kim@company.com',
    role: 'Mobile Developer',
    country: 'United States',
    annualSalary: 110000,
    dateOfJoining: new Date('2020-02-15').toISOString(),
    hireType: 'Agency',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-05-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP034',
    name: 'Elena Popescu',
    email: 'elena.popescu@company.com',
    role: 'QA Engineer',
    country: 'Romania',
    annualSalary: 59000,
    dateOfJoining: new Date('2021-10-05').toISOString(),
    hireType: 'Direct',
    contractType: 'Contract',
    contractEndDate: new Date('2023-10-05').toISOString(),
    probationEndDate: new Date('2022-01-05').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP035',
    name: 'Kenji Yamamoto',
    email: 'kenji.yamamoto@company.com',
    role: 'Security Engineer',
    country: 'Japan',
    annualSalary: 92000,
    dateOfJoining: new Date('2019-11-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-02-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP036',
    name: 'Zoe Anderson',
    email: 'zoe.anderson@company.com',
    role: 'Content Strategist',
    country: 'New Zealand',
    annualSalary: 69000,
    dateOfJoining: new Date('2021-04-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-07-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP037',
    name: 'Mohammed Al-Farsi',
    email: 'mohammed.alfarsi@company.com',
    role: 'Frontend Developer',
    country: 'Saudi Arabia',
    annualSalary: 68000,
    dateOfJoining: new Date('2020-08-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-11-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP038',
    name: 'Julia Nowak',
    email: 'julia.nowak@company.com',
    role: 'Business Analyst',
    country: 'Poland',
    annualSalary: 64000,
    dateOfJoining: new Date('2021-07-01').toISOString(),
    hireType: 'Agency',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-10-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP039',
    name: 'Gabriel Costa',
    email: 'gabriel.costa@company.com',
    role: 'DevOps Engineer',
    country: 'Brazil',
    annualSalary: 75000,
    dateOfJoining: new Date('2020-05-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-08-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP040',
    name: 'Amara Okonkwo',
    email: 'amara.okonkwo@company.com',
    role: 'Product Manager',
    country: 'Nigeria',
    annualSalary: 82000,
    dateOfJoining: new Date('2019-12-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-03-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP041',
    name: 'Erik Johansson',
    email: 'erik.johansson@company.com',
    role: 'Backend Developer',
    country: 'Sweden',
    annualSalary: 77000,
    dateOfJoining: new Date('2020-10-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-01-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP042',
    name: 'Lily Zhang',
    email: 'lily.zhang@company.com',
    role: 'UI Designer',
    country: 'China',
    annualSalary: 70000,
    dateOfJoining: new Date('2021-02-05').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-05-05').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP043',
    name: 'Mateo Fernandez',
    email: 'mateo.fernandez@company.com',
    role: 'Software Engineer',
    country: 'Argentina',
    annualSalary: 64000,
    dateOfJoining: new Date('2022-03-15').toISOString(),
    hireType: 'Direct',
    contractType: 'Contract',
    contractEndDate: new Date('2023-03-15').toISOString(),
    probationEndDate: new Date('2022-06-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP044',
    name: 'Rebecca Johnson',
    email: 'rebecca.johnson@company.com',
    role: 'HR Specialist',
    country: 'United States',
    annualSalary: 72000,
    dateOfJoining: new Date('2020-06-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-09-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP045',
    name: 'Vikram Patel',
    email: 'vikram.patel@company.com',
    role: 'Senior Data Scientist',
    country: 'India',
    annualSalary: 95000,
    dateOfJoining: new Date('2019-08-12').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-11-12').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP046',
    name: 'Sophie Laurent',
    email: 'sophie.laurent@company.com',
    role: 'Marketing Specialist',
    country: 'France',
    annualSalary: 66000,
    dateOfJoining: new Date('2021-09-15').toISOString(),
    hireType: 'Agency',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2021-12-15').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP047',
    name: 'Daniel Muller',
    email: 'daniel.muller@company.com',
    role: 'Senior Software Engineer',
    country: 'Germany',
    annualSalary: 105000,
    dateOfJoining: new Date('2019-02-20').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2019-05-20').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP048',
    name: 'Nicole Thompson',
    email: 'nicole.thompson@company.com',
    role: 'Customer Success Manager',
    country: 'Australia',
    annualSalary: 84000,
    dateOfJoining: new Date('2020-01-10').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2020-04-10').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP049',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@company.com',
    role: 'QA Engineer',
    country: 'Japan',
    annualSalary: 69000,
    dateOfJoining: new Date('2021-11-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-02-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
  {
    id: 'EMP050',
    name: 'Samuel Osei',
    email: 'samuel.osei@company.com',
    role: 'Frontend Developer',
    country: 'Ghana',
    annualSalary: 61000,
    dateOfJoining: new Date('2022-02-01').toISOString(),
    hireType: 'Direct',
    contractType: 'Permanent',
    contractEndDate: '',
    probationEndDate: new Date('2022-05-01').toISOString(),
    manager: {} as Employee, // Will be linked below,
  },
];

// Linking managers
// CTO has no manager
mockEmployees[4].manager = {} as Employee;

// CFO reports to CTO
mockEmployees[14].manager = mockEmployees[4];

// Department managers report to C-level executives
mockEmployees[1].manager = mockEmployees[4]; // Engineering Manager → CTO
mockEmployees[3].manager = mockEmployees[4]; // Product Manager → CTO
mockEmployees[9].manager = mockEmployees[14]; // HR Manager → CFO
mockEmployees[22].manager = mockEmployees[14]; // Sales Manager → CFO
mockEmployees[27].manager = mockEmployees[14]; // Marketing Manager → CFO

// Team leads and senior staff
mockEmployees[0].manager = mockEmployees[1]; // Senior SWE → Engineering Manager
mockEmployees[19].manager = mockEmployees[3]; // Senior UX Designer → Product Manager
mockEmployees[30].manager = mockEmployees[1]; // Senior Backend Developer → Engineering Manager
mockEmployees[44].manager = mockEmployees[1]; // Senior Data Scientist → Engineering Manager
mockEmployees[46].manager = mockEmployees[1]; // Senior SWE → Engineering Manager
mockEmployees[29].manager = mockEmployees[9]; // Customer Support Lead → HR Manager
mockEmployees[47].manager = mockEmployees[22]; // Customer Success Manager → Sales Manager

// Regular employees
mockEmployees[2].manager = mockEmployees[1]; // Frontend Dev → Engineering Manager
mockEmployees[5].manager = mockEmployees[1]; // Backend Dev → Engineering Manager
mockEmployees[6].manager = mockEmployees[44]; // Data Scientist → Senior Data Scientist
mockEmployees[7].manager = mockEmployees[19]; // UX Designer → Senior UX Designer
mockEmployees[8].manager = mockEmployees[1]; // DevOps Engineer → Engineering Manager
mockEmployees[10].manager = mockEmployees[0]; // Software Engineer → Senior SWE
mockEmployees[11].manager = mockEmployees[27]; // Marketing Specialist → Marketing Manager
mockEmployees[12].manager = mockEmployees[1]; // QA Engineer → Engineering Manager
mockEmployees[13].manager = mockEmployees[0]; // Frontend Dev → Senior SWE
mockEmployees[15].manager = mockEmployees[27]; // Content Writer → Marketing Manager
mockEmployees[16].manager = mockEmployees[30]; // Backend Dev → Senior Backend Dev
mockEmployees[17].manager = mockEmployees[44]; // Data Analyst → Senior Data Scientist
mockEmployees[18].manager = mockEmployees[3]; // Project Manager → Product Manager
mockEmployees[20].manager = mockEmployees[8]; // DevOps Engineer → DevOps Engineer
mockEmployees[21].manager = mockEmployees[19]; // Product Designer → Senior UX Designer
mockEmployees[23].manager = mockEmployees[19]; // Graphic Designer → Senior UX Designer
mockEmployees[24].manager = mockEmployees[46]; // Software Engineer → Senior SWE
mockEmployees[25].manager = mockEmployees[0]; // Frontend Dev → Senior SWE
mockEmployees[26].manager = mockEmployees[1]; // System Admin → Engineering Manager
mockEmployees[28].manager = mockEmployees[44]; // Data Scientist → Senior Data Scientist
mockEmployees[31].manager = mockEmployees[30]; // Junior SWE → Senior Backend Dev
mockEmployees[32].manager = mockEmployees[0]; // Mobile Dev → Senior SWE
mockEmployees[33].manager = mockEmployees[12]; // QA Engineer → QA Engineer
mockEmployees[34].manager = mockEmployees[1]; // Security Engineer → Engineering Manager
mockEmployees[35].manager = mockEmployees[27]; // Content Strategist → Marketing Manager
mockEmployees[36].manager = mockEmployees[25]; // Frontend Dev → Frontend Dev
mockEmployees[37].manager = mockEmployees[18]; // Business Analyst → Project Manager
mockEmployees[38].manager = mockEmployees[8]; // DevOps Engineer → DevOps Engineer
mockEmployees[39].manager = mockEmployees[3]; // Product Manager → Product Manager
mockEmployees[40].manager = mockEmployees[30]; // Backend Dev → Senior Backend Dev
mockEmployees[41].manager = mockEmployees[19]; // UI Designer → Senior UX Designer
mockEmployees[42].manager = mockEmployees[46]; // Software Engineer → Senior SWE
mockEmployees[43].manager = mockEmployees[9]; // HR Specialist → HR Manager
mockEmployees[45].manager = mockEmployees[27]; // Marketing Specialist → Marketing Manager
mockEmployees[48].manager = mockEmployees[12]; // QA Engineer → QA Engineer
mockEmployees[49].manager = mockEmployees[0]; // Frontend Dev → Senior SWE

export default mockEmployees;
